### ISSUE TITLE
Compile of Angular app not possible since update to v3.2.x

### ISSUE THREAD

**Issue by heinerlamprecht** [cure53/DOMPurify#1035]
### Background & Context

We tried to update from v3.17 to v3.20 or v3.2.1, but the compile of our Angular app fails. Installing @types/trusted-types 2.0.7 does not change anything.

### Bug

When running the build. the following error message appears:

```
> ng-web@3.5.0 build:app
> ng build in-web-app --configuration production --aot

✔ Browser application bundle generation complete.

Error: node_modules/dompurify/dist/purify.es.d.mts:170:28 - error TS2304: Cannot find name 'TrustedTypePolicy'.

170     TRUSTED_TYPES_POLICY?: TrustedTypePolicy | undefined;
                               ~~~~~~~~~~~~~~~~~


Error: node_modules/dompurify/dist/purify.es.d.mts:245:9 - error TS2304: Cannot find name 'TrustedHTML'.

245     }): TrustedHTML;
            ~~~~~~~~~~~


Error: node_modules/dompurify/dist/purify.es.d.mts:396:34 - error TS2339: Property 'trustedTypes' does not exist on type 'Window & typeof globalThis'.

396     trustedTypes?: typeof window.trustedTypes;
                                     ~~~~~~~~~~~~

```

#### Input

n/a

#### Given output

n/a

#### Expected output

no build error

### Feature

n/a

**Comment by ghiscoding** [comment]
@heinerlamprecht you should also make sure that your `tsconfig` has `"lib": [dom]` and it might also require `@types/node` though I'm not sure about this last one. My Angular project is building correctly after v3.2.1 (it was failing in v3.2.0 with different error). `TrustedTypePolicy` and `TrustedHTML` are global types but I assume it requires certain configuration of tsconfig and certain `@types` to be installed as well

**Comment by reduckted** [comment]
@heinerlamprecht Can you provide a reproduction, please?

**Comment by Athov** [comment]
Hello, I have the same issue:

```

✔ Browser application bundle generation complete.

Error: node_modules/@tinkoff/ng-dompurify/lib/types/dompurify-hook.d.ts:1:18 - error TS2305: Module '"dompurify"' has no exported member 'HookEvent'.

1 import { Config, HookEvent } from 'dompurify';
                    ~~~~~~~~~


Error: node_modules/dompurify/dist/purify.cjs.d.ts:170:28 - error TS2304: Cannot find name 'TrustedTypePolicy'.

170     TRUSTED_TYPES_POLICY?: TrustedTypePolicy | undefined;
                                ~~~~~~~~~~~~~~~~~


Error: node_modules/dompurify/dist/purify.cjs.d.ts:245:9 - error TS2304: Cannot find name 'TrustedHTML'.

245     }): TrustedHTML;
             ~~~~~~~~~~~

Error: node_modules/dompurify/dist/purify.cjs.d.ts:396:34 - error TS2339: Property 'trustedTypes' does not exist on type 'Window & typeof globalThis'.

396     trustedTypes?: typeof window.trustedTypes;
                                      ~~~~~~~~~~~~

```

I have everything in ```tsconfig```  also have the ```@types``` installed:

    "@types/dompurify": "^3.2.0",
    "@types/node": "^20.17.7",
    "@types/trusted-types": "^2.0.7",
    
At the moment I have downgraded to v3.1.7

**Comment by reduckted** [comment]
Please provide a reproduction. Without one, there's nothing we can do.

**Comment by DanielSchiavini** [comment]
The package after install does not contain any type definitions
![image](https://github.com/user-attachments/assets/fc628da8-3209-463b-925b-08c988544a7b)

**Comment by reduckted** [comment]
@DanielSchiavini You have [file nesting](https://code.visualstudio.com/updates/v1_67#_explorer-file-nesting) enabled.

**Comment by DanielSchiavini** [comment]
> ###
> **[reduckted](/reduckted) ** commented [Nov 25, 2024](#issuecomment-2497582985)

I don't use VSCode. Folder contents:
```
$ ls node_modules/dompurify/**/*
node_modules/dompurify/dist/purify.cjs.d.ts    node_modules/dompurify/dist/purify.es.mjs      node_modules/dompurify/dist/purify.min.js
node_modules/dompurify/dist/purify.cjs.js      node_modules/dompurify/dist/purify.es.mjs.map  node_modules/dompurify/dist/purify.min.js.map
node_modules/dompurify/dist/purify.cjs.js.map  node_modules/dompurify/dist/purify.js
node_modules/dompurify/dist/purify.es.d.mts    node_modules/dompurify/dist/purify.js.map
```

**Comment by reduckted** [comment]
@heinerlamprecht Thanks for the reproduction. I also had to `npm i @ngstack/translate` to get it to compile, but I was able to reproduce the problem with it after that 😄 

Installing `@types/trusted-types` didn't solve the problem, which is very interesting. 😕 There must be some combination of Angular and/or TypeScript compilation settings that cause them to not be used in this situation. I think I've found the solution though - #1036.

As a workaround until that's merged and released, if it doesn't affect anything else in your application, you can add [`skipLibCheck`](https://www.typescriptlang.org/tsconfig/#skipLibCheck) to the TypeScript compilation options.

**Comment by heinerlamprecht** [comment]
@reduckted thanks for the update and the fix.

**Comment by cure53** [comment]
Is it safe to go for another release? :sweat_smile:

**Comment by donmccurdy** [comment]
After running into very similar-sounding issues in a React application, I've opened a pull request here:

- https://github.com/cure53/DOMPurify/pull/1073

Not sure if this would affect the Angular issue described here, but it's easy to test by making the same change in the `.d.ts` files in `node_modules`, replacing 'trusted-types' with 'trusted-types/lib'.

**Comment by cure53** [comment]
cc @reduckted and @heinerlamprecht please, thanks 😄
