### ISSUE TITLE
Cannot find type definition file for 'dompurify'

### ISSUE THREAD

**Issue by whoisahmed** [cure53/DOMPurify#1063]
Hello,
After upgrading from v2.5.6 to v3.2.4, I'm getting this issue when I run `ts-compile`

```
error TS2688: Cannot find type definition file for 'dompurify'.
  The file is in the program because:
    Entry point for implicit type library 'dompurify'
```

packages:
```
"dompurify": "3.2.4",
"@types/dompurify": "3.2.0",
```

Can you please help?

**Comment by cure53** [comment]
We ship our own types now, maybe you can slim down the package file a bit and then it works?

**Comment by whoisahmed** [comment]
@cure53 thanks for your reply.
but How do I slim down it pls?

**Comment by cure53** [comment]
As mentioned, we ship our own types now, no need to import them any longer.  

https://www.npmjs.com/package/@types/dompurify

> This is a stub types definition for @types/dompurify (https://github.com/cure53/DOMPurify).
> dompurify provides its own type definitions, so you don't need @types/dompurify installed!

**Comment by whoisahmed** [comment]
@cure53
It works now, thanks so much!  🙏

**Comment by cure53** [comment]
Awesome 😄
